# Generated by Django 3.2.5 on 2021-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcut_name', models.CharField(max_length=20)),
                ('prodcut_description', models.CharField(max_length=50)),
            ],
        ),
    ]
