# Generated by Django 3.2.5 on 2021-08-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210729_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.DecimalField(decimal_places=11, max_digits=11)),
                ('query', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
