# Generated by Django 3.2.5 on 2021-08-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=15)),
                ('state', models.CharField(default='', max_length=15)),
                ('zip', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
