# Generated by Django 3.2.5 on 2021-08-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_order',
            fields=[
                ('update_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(max_length=10)),
                ('update_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
