# Generated by Django 3.2.5 on 2021-08-08 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_update_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='update_order',
            name='timestamps',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
